name: ds_prod
dependencies:
- flask
- pip:
  - sklearn
  - dill
  - numpy
  - pandas
  - scipy
  - git+https://github.com/BigDataRepublic/bdr-engineering-stack.git@Feature/model_docker#subdirectory=data-science-production-container/ds_prod_api

